### ISSUE TITLE
Reason to expose port 22?

### ISSUE THREAD

**Issue by xuhdev** [blankoworld/docker-isso#1]
I don't think it's a good thing to run sshd inside a container, especially it is not needed here..

**Comment by dashohoxha** [comment]
And also I think that it is useless, it is not going to start.

**Comment by blankoworld** [comment]
Hi all.

I was the only solution that works when I attempt to access the container to see why the Isso server doesn't work.

But you're right, it shouldn't be available in this docker.

**Comment by dashohoxha** [comment]
I install the command **docker-enter** like this:
`docker run -v /usr/local/bin:/target jpetazzo/nsenter`

Then access the container like this: `docker-enter isso`
(this is similar to `chroot /path/to/chroot-dir`).
